# The products page of the website (docs/, Quarto): the records of the registry, one
# section per dataset and record, with the files of each grid and their download links.
# Written to docs/_products.md, which docs/products.qmd includes. Standard library only.

include(joinpath(@__DIR__, "catalog.jl"))

esc(s) = replace(string(s), "&" => "&amp;", "<" => "&lt;", ">" => "&gt;", "\"" => "&quot;")

"Page of a dataset on the website (docs/datasets/<name>.qmd)."
dataset_page(dataset::AbstractString) = "datasets/$(lowercase(dataset)).qmd"

"A record: its release, the download commands, and the files of each grid (HTML)."
function record_html(io::IO, domain::AbstractString, dataset::AbstractString)
    tables, files = read_record(domain, dataset)
    release, zenodo = tables["_RELEASE"], get(tables, "_ZENODO", nothing)
    doi(d) = "<a href=\"https://doi.org/$(esc(d))\">doi:$(esc(d))</a>"
    archive = zenodo === nothing ? "" :
        zenodo["git_tag"] == release["git_tag"] ? "; $(doi(zenodo["doi"])) (all versions: $(doi(zenodo["concept_doi"])))" :
        "; archived versions: $(doi(zenodo["concept_doi"]))"
    grids = record_grids(files)
    println(io, "<div class=\"record\">")
    println(io, "<p>Version $(esc(release["version"])) ($(esc(release["date"])), ",
            "<a href=\"$(esc(release["store"]))\">packages</a>$archive). ",
            "$(length(files)) files, $(human_size(total_size(values(files)))).</p>")
    println(io, "<pre>julia fesmdata.jl fetch $(esc(dataset)) $(esc(domain))     # all grids\n",
            "julia fesmdata.jl fetch $(esc(dataset)) $(esc(first(last(grids))))     # one grid</pre>")
    for (grid, entries) in grids
        println(io, "<details><summary><b>$(esc(grid))</b> <span class=\"muted\">",
                "$(length(entries)) files, $(human_size(total_size(last.(entries))))</span></summary><table>")
        for (name, e) in entries
            println(io, "<tr><td><a href=\"$(esc(e["uri"]))\">$(esc(name))</a></td>",
                    "<td class=\"size\">$(human_size(get(e, "size", 0)))</td></tr>")
        end
        println(io, "</table></details>")
    end
    println(io, "</div>")
end

"""
    write_products(path)

Write the products page (Markdown with HTML blocks) to `path`: for each dataset of
datasets.toml, its description and records.
"""
function write_products(path::AbstractString)
    datasets = TOML.parsefile(joinpath(@__DIR__, "datasets.toml"))
    records = list_records()
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, """
            <!-- Generated by `julia fesmdata.jl docs` from registry/ (do not edit). -->

            The released records of each dataset, one per domain. Each grid has its own
            files: its grid description for cdo (`grid_<GRID>.txt`), its grid file
            (`<GRID>_grid.nc`) and the products. Download them with `fesmdata.jl` into
            `\$ICE_DATA/v2/<Domain>/<GRID>/` (see [Getting started](index.qmd)), or file by
            file from the links below.
            """)
        for dataset in sort(filter(!startswith("_"), collect(keys(datasets))))
            cfg = datasets[dataset]
            println(io, "\n## $dataset: $(cfg["title"])\n")
            println(io, strip(replace(cfg["description"], '\n' => ' ')),
                    " See [how it is made]($(dataset_page(dataset))).\n")
            recs = [d for (d, s) in records if s == dataset]
            isempty(recs) && println(io, "*Not released yet.*\n")
            for domain in recs
                println(io, "\n### $domain\n\n```{=html}")
                record_html(io, domain, dataset)
                println(io, "```\n")
            end
        end
    end
    return path
end
